name: Bump version

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: dev
      node-version:
        type: string
        default: 20
      bump-command:
        type: string
        default: npm version patch --no-git-tag-version

jobs:

  setup:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: node-modules-cache-node-${{ env.NODE_VERSION }}-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Get version
        run: echo VERSION=$(node -p 'require("./package.json").version') >> $GITHUB_ENV

      - name: Commit and push
        run: |
          git config --local user.email "version-bumpooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          git add package.json package-lock.json
          git commit -m "chore: release v${{ env.VERSION }}"
          git tag v${{ env.VERSION }}
          git push origin ${{ inputs.ref }} --tags
