name: Deploy

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: dev
    secrets:
      token:
        required: true

jobs:

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.token }}'
          ref: ${{ inputs.ref }}

      - name: ls
        run: ls -la code
