name: Deploy latest image to staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production # used to fetch the secrets from
    steps:
      - name: Trigger webhook
        run: curl -X POST ${{ secrets.STAGING_DEPLOY_WEBHOOK }}
