name: Fast-forward dev to master

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  fast-forward:
    uses: ./.github/workflows/w-fast-forward.yml
    with:
      environment: production
      source-ref: dev
      target-ref: master
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}

  tag-image:
    uses: ./.github/workflows/w-tag-image.yml
    with:
      environment: production
      image: ${{ github.repository }}
      ref: master
      target-tag: latest
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}
