name: Merge to dev

on:
  push:
    branches: ['*']

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  bump:
    uses: ./.github/workflows/bump.yml
    with:
      ref: dev
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pre-build:
    runs-on: ubuntu-22.04
    outputs:
      registry: ${{ steps.vars.outputs.REGISTRY }}
    steps:
      - name: Prepare vars
        id: vars
        run: echo "REGISTRY=${{ env.REGISTRY }}" >> $GITHUB_OUTPUT
      - name: Check registry
        if: steps.vars.outputs.REGISTRY != ''
        run: echo OK

  build:
    uses: ./.github/workflows/build.yml
    needs: pre-build
    with:
      registry: ${{ needs.pre-build.outputs.registry }}
      app-name: dummy-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  post-build:
    environment: production
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Print output tag
        run: echo "The output tag is '${{ needs.build.outputs.image-tag }}'"
