name: Merge to dev

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  reset-release-candidate:
    uses: ./.github/workflows/w-reset.yml
    with:
      target-ref: release-candidate
      base-ref: dev
      environment: production
    secrets:
      DEPLOYER_APP_ID: ${{ secrets.DEPLOYER_APP_ID }}
      DEPLOYER_APP_PK: ${{ secrets.DEPLOYER_APP_PK }}


