name: Merge to dev

on:
  push:
    branches: ['*']

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: dev
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-22.04
    needs: build

    steps:

      - name: Print output tag
        run: echo "The output tag is '${{ needs.build.outputs.image-tag }}'"
