name: Merge PR to dev

on:
  push:
    branches: [dev]

jobs:
  bump:
    uses: ./.github/workflows/w-bump.yml
    with:
      ref: dev
      bump-command: npm version patch --no-git-tag-version
      environment: production
    secrets:
      DEPLOYER_APP_ID: true
      DEPLOYER_APP_PK: true

  build:
    needs: bump
    uses: ./.github/workflows/w-build.yml
    with:
      environment: production
      ref: dev
      image: dummy-app
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: true
      DOCKER_PASSWORD: true

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    environment: staging
    steps:
        - name: Deploy to staging
          run: |
            curl -X POST ${{ secrets.STAGING_DEPLOY_WEBHOOK }}
