name: Merge PR to dev

on:
  push:
    branches: [dev]

jobs:
  bump:
    uses: ./.github/workflows/w-bump.yml
    with:
      ref: dev
      bump-command: npm version patch --no-git-tag-version
    secrets:
      deployer-app-id: ${{ secrets.DEPLOYER_APP_ID }}
      deployer-app-pk: ${{ secrets.DEPLOYER_APP_PK }}

  build:
    needs: bump
    uses: ./.github/workflows/w-build.yml
    with:
      ref: dev
      registry: ${{ secrets.REGISTRY }}
      app-name: dummy-app
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    uses: ./.github/workflows/w-deploy.yml
    with:
      ref: dev
      environment: staging
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
