name: Merge to dev

on:
  push:
    branches: ['*']

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        with:
          script: console.log(JSON.stringify(github, null, 2));
      - uses: actions/github-script@v7
        with:
          script: console.log(JSON.stringify(context, null, 2));

#          script: |
#            github.rest.repos.createDispatchEvent({
#              owner: context.repo.owner,
#              repo: 'workflows',
#              event_type: 'build',
#              client_payload: { repo: context.repo.repo, branch: context.ref_name }
#            });
