name: Merge to dev

on:
  push:
    branches: ['*']

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: NexusMutual/workflows/.github/workflows/build.yml@master
    with:
      repo: ${{ github.repository }}
      branch: ${{ github.ref }}
