name: Merge to dev or master

on:
  push:
    branches:
      - master
      - dev

jobs:
  bump:
    uses: ./.github/workflows/w-bump.yml
    with:
      ref: ${{ github.ref_name }}
      bump-command: npm version patch --no-git-tag-version
      environment: production
    secrets:
      DEPLOYER_APP_ID: true
      DEPLOYER_APP_PK: true

  build:
    needs: bump
    uses: ./.github/workflows/w-build.yml
    with:
      ref: ${{ github.ref_name }}
      environment: production
      image: ${{ github.repository }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: true
      DOCKER_PASSWORD: true

  rebase-dev:
    needs: build
    if: github.ref_name == 'master'
    uses: ./.github/workflows/w-rebase.yml
    with:
      target-ref: dev
      base-ref: master
      environment: production
    secrets:
      DEPLOYER_APP_ID: true
      DEPLOYER_APP_PK: true
