name: Merge to dev

on:
  push:
    branches: ['*']

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.REQUESTOR_APP_ID }}
          private-key: ${{ secrets.REQUESTOR_APP_PK }}
          owner: ${{ github.repository_owner }}
          repositories:
            - workflows

      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const repo = context.repo.repo;
            const [,,branch] = context.ref.split('/');
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'workflows',
              event_type: 'build',
              client_payload: { repo, branch }
            });
