name: Merge PR to master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  bump:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/w-bump.yml
    with:
      ref: master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: bump
    uses: ./.github/workflows/w-build.yml
    with:
      ref: master
      registry: ${{ secrets.REGISTRY }}
      app-name: dummy-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  rebase-dev:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase dev on master
        run: |
          (
            git fetch origin
            git rebase origin/master
            git push origin dev --force
          ) || true
