name: Bump version

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      node-version:
        type: string
        default: 20
      bump-command:
        type: string
        default: npm version patch --no-git-tag-version
    secrets:
      token:
        required: true

jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Get package.json version
        run: echo VERSION=$(node -p 'require("./package.json").version') >> $GITHUB_ENV

      - name: Commit, tag and push
        run: |
          git config --local user.email "version-bumpooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          git add package.json package-lock.json
          git commit -m "chore: release v${{ env.VERSION }}"
          git tag v${{ env.VERSION }}
          git push origin ${{ inputs.ref }} --tags
