name: Bump version

on:
  workflow_call:
    inputs:
#      repository:
#        type: string
#        required: true
      ref:
        type: string
        required: true
      bump-command:
        type: string
      node-version:
        type: string
        default: 20
    secrets:
      deployer-app-id:
        required: true
      deployer-app-pk:
        required: true

jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.deployer-app-id }}
          private-key: ${{ secrets.deployer-app-pk }}
          #repositories: ${{ inputs.repository }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit --no-fund

      - name: Bump version
        run: ${{ inputs.bump-command }}

      - name: Get package.json version
        run: echo VERSION=$(node -p 'require("./package.json").version') >> $GITHUB_ENV

      - name: Commit, tag and push
        run: |
          git config --local user.email "version-bumpooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          git add -a
          git commit -m "chore: release v${{ env.VERSION }}"
          git tag v${{ env.VERSION }}
          git push origin ${{ inputs.ref }} --tags
