name: Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      registry:
        type: string
        required: true
      image:
        type: string
        required: true
      dockerfile:
        type: string
        default: Dockerfile
      node-version:
        type: string
        default: 20
    secrets:
      github-token:
        required: true
    outputs:
      image-tag:
        value: ${{ jobs.build.outputs.image-tag }}

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      image-tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Get version and revision
        id: vars
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "TAG=${VERSION}-${SHA_SHORT}" >> $GITHUB_OUTPUT

      - name: Build image
        env:
          REGISTRY: ${{ inputs.registry }}
          IMAGE: ${{ inputs.image }}
          TAG: ${{ steps.vars.outputs.TAG }}
        run: docker build -t "${REGISTRY}/${IMAGE}:${TAG}" -f ${{ inputs.dockerfile }} .

      - name: Push image
        env:
          REGISTRY: ${{ inputs.registry }}
          IMAGE: ${{ inputs.image }}
          TAG: ${{ steps.vars.outputs.TAG }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker push "${REGISTRY}/${IMAGE}:${TAG}"

      - name: Print tag
        run: echo "The image tag is '${{ steps.vars.outputs.TAG }}'"
