name: Deploy

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      environment:
        type: string
        required: true
      image-tag:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}'/argocd
          token: ${{ secrets.token }}
          ref: ${{ inputs.ref }}

      - name: Deploy to ArgoCD
        run: |
          echo "Updating ArgoCD with image tag ${{ inputs.image-tag }} for environment ${{ inputs.environment }}"
          # Add your ArgoCD deployment logic here
