name: Deploy master branch to prod

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.token }}'
          ref: master

      - name: Fast forward dev to master
        run: "echo 'TODO: implement argocd commit using app'"
