name: Tag Image

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      image:
        type: string
        required: true
      source-tag:
        type: string
        required: true
      target-tag:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    outputs:
      image-tag:
        value: ${{ jobs.build.outputs.image-tag }}

jobs:
  tag-image:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Tag image
        env:
          IMAGE: ${{ inputs.image }}
          SOURCE_TAG: ${{ inputs.source-tag }}
          TARGET_TAG: ${{ inputs.taget-tag }}
        run: docker buildx imagetools create ghcr.io/${IMAGE}:${SOURCE_TAG} --tag ghcr.io/${IMAGE}:${TARGET_TAG} .

      - name: Push tag
        env:
          IMAGE: ${{ inputs.image }}
          TAG: ${{ inputs.taget-tag }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "ghcr.io/${IMAGE}:${TAG}"

      - name: Print tag
        run: echo "Pushed ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}"
